version: '3.1'
services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 5000:5000
    environment:
      - MONGO_INITDB_ROOT_USERNAME=revolut
      - MONGO_INITDB_ROOT_PASSWORD=revolut
      - MONGO_INITDB_DATABASE=revolut
    networks:
      - revolut
            
  ddbb:
    container_name: ddbb
    image: mongo:6.0.1
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=revolut
      - MONGO_INITDB_ROOT_PASSWORD=revolut
    networks:
      - revolut

      
networks:
  revolut:
    name: revolut